name: run
on:
  push:
  schedule:
    - cron: '00 01 * * *'
concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Git
      uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get install -y libcurl4-openssl-dev
    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.2.1'
    - name: Setup renv
      uses: r-lib/actions/setup-renv@v2
      with:
        cache-version: 0
      env:
        RENV_CONFIG_REPOS_OVERRIDE: "https://packagemanager.rstudio.com/all/latest"
    - name: Run apto
      run: Rscript main.R
      env:
        R_TELEGRAM_BOT_aptobot: ${{ secrets.R_TELEGRAM_BOT_aptobot }}
